import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

import { Share } from '@capacitor/share';

import { IonHeader, IonTitle, IonToolbar, IonButton } from '@ionic/react';
import { Capacitor } from '@capacitor/core';

const Home: NextPage = () => {
  const share = async () => {
    await Share.share({
      title: 'Felipe DEV UX Software',
      text: 'Felipe tá desenvolvendo uns app massa!!!',
      url: 'https://www.instagram.com/felipe_barros._/',
      dialogTitle: 'Compartilhar com amigos',
    });
  };

  return (
    <div>
      <Head>
        <title>Create Capacitor App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, viewport-fit=cover"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {Capacitor.isNativePlatform() && (
        <IonHeader>
          <IonToolbar color="primary">
            <IonTitle>Felipe Capacitor App</IonTitle>
          </IonToolbar>
        </IonHeader>
      )}

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Capacitor.js!</a> by Felipe
        </h1>
        <IonButton
          color="success"
          expand="block"
          mode="ios"
          onClick={() => share()}
        >
          Compartilhe agora!!!
        </IonButton>
      </main>
    </div>
  );
};

export default Home;
