import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import { Share } from '@capacitor/share';

const Home: NextPage = () => {
  const share = async () => {
    await Share.share({
      title: 'Felipe DEV UX Software',
      text: 'Felipe tá desenvolvendo uns app massa!!!',
      url: 'https://www.instagram.com/felipe_barros._/',
      dialogTitle: 'Compartilhar com amigos',
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Capacitor App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Capacitor.js!</a> by Felipe
        </h1>
        <br />
        <br />
        <h1 className={styles.title}>
          <a onClick={() => share()}>Compartilhe agora!!!</a>
        </h1>
      </main>
    </div>
  );
};

export default Home;
